// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: kms.proto

package crypto

import (
	context "context"
	proto "github.com/GTLiSunnyi/cita-sdk-go/protos/proto"
	types "github.com/GTLiSunnyi/cita-sdk-go/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCryptoInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       *proto.StatusCode `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name         string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	HashLen      uint32            `protobuf:"varint,3,opt,name=hash_len,json=hashLen,proto3" json:"hash_len,omitempty"`
	SignatureLen uint32            `protobuf:"varint,4,opt,name=signature_len,json=signatureLen,proto3" json:"signature_len,omitempty"`
	AddressLen   uint32            `protobuf:"varint,5,opt,name=address_len,json=addressLen,proto3" json:"address_len,omitempty"`
}

func (x *GetCryptoInfoResponse) Reset() {
	*x = GetCryptoInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCryptoInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoInfoResponse) ProtoMessage() {}

func (x *GetCryptoInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCryptoInfoResponse) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{0}
}

func (x *GetCryptoInfoResponse) GetStatus() *proto.StatusCode {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetCryptoInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCryptoInfoResponse) GetHashLen() uint32 {
	if x != nil {
		return x.HashLen
	}
	return 0
}

func (x *GetCryptoInfoResponse) GetSignatureLen() uint32 {
	if x != nil {
		return x.SignatureLen
	}
	return 0
}

func (x *GetCryptoInfoResponse) GetAddressLen() uint32 {
	if x != nil {
		return x.AddressLen
	}
	return 0
}

type GenerateKeyPairRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
}

func (x *GenerateKeyPairRequest) Reset() {
	*x = GenerateKeyPairRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairRequest) ProtoMessage() {}

func (x *GenerateKeyPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairRequest) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKeyPairRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GenerateKeyPairResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId   uint64 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GenerateKeyPairResponse) Reset() {
	*x = GenerateKeyPairResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKeyPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKeyPairResponse) ProtoMessage() {}

func (x *GenerateKeyPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKeyPairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKeyPairResponse) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateKeyPairResponse) GetKeyId() uint64 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *GenerateKeyPairResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

type HashDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HashDataRequest) Reset() {
	*x = HashDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashDataRequest) ProtoMessage() {}

func (x *HashDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashDataRequest.ProtoReflect.Descriptor instead.
func (*HashDataRequest) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{3}
}

func (x *HashDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VerifyDataHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *VerifyDataHashRequest) Reset() {
	*x = VerifyDataHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyDataHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDataHashRequest) ProtoMessage() {}

func (x *VerifyDataHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDataHashRequest.ProtoReflect.Descriptor instead.
func (*VerifyDataHashRequest) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyDataHashRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VerifyDataHashRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SignMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyId uint64 `protobuf:"varint,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Msg   []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SignMessageRequest) Reset() {
	*x = SignMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageRequest) ProtoMessage() {}

func (x *SignMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageRequest.ProtoReflect.Descriptor instead.
func (*SignMessageRequest) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{5}
}

func (x *SignMessageRequest) GetKeyId() uint64 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *SignMessageRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type SignMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    *proto.StatusCode `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Signature []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *SignMessageResponse) Reset() {
	*x = SignMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageResponse) ProtoMessage() {}

func (x *SignMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignMessageResponse.ProtoReflect.Descriptor instead.
func (*SignMessageResponse) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{6}
}

func (x *SignMessageResponse) GetStatus() *proto.StatusCode {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SignMessageResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RecoverSignatureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *RecoverSignatureRequest) Reset() {
	*x = RecoverSignatureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverSignatureRequest) ProtoMessage() {}

func (x *RecoverSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverSignatureRequest.ProtoReflect.Descriptor instead.
func (*RecoverSignatureRequest) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{7}
}

func (x *RecoverSignatureRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RecoverSignatureRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type RecoverSignatureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *proto.StatusCode `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Address []byte            `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *RecoverSignatureResponse) Reset() {
	*x = RecoverSignatureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kms_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecoverSignatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverSignatureResponse) ProtoMessage() {}

func (x *RecoverSignatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kms_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverSignatureResponse.ProtoReflect.Descriptor instead.
func (*RecoverSignatureResponse) Descriptor() ([]byte, []int) {
	return file_kms_proto_rawDescGZIP(), []int{8}
}

func (x *RecoverSignatureResponse) GetStatus() *proto.StatusCode {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RecoverSignatureResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_kms_proto protoreflect.FileDescriptor

var file_kms_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6b, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6b, 0x6d, 0x73,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb8, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61,
	0x73, 0x68, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x68, 0x61,
	0x73, 0x68, 0x4c, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4c, 0x65, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x16, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4a, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x25, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3f, 0x0a, 0x15, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x3d, 0x0a, 0x12, 0x53,
	0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5f, 0x0a, 0x13, 0x53, 0x69,
	0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x49, 0x0a, 0x17, 0x52,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x60, 0x0a, 0x18, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0xe9, 0x03, 0x0a, 0x0a, 0x4b, 0x6d, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x12, 0x1b, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x4b, 0x65, 0x79, 0x50, 0x61, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x36, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x2e,
	0x6b, 0x6d, 0x73, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1a, 0x2e, 0x6b, 0x6d,
	0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x48, 0x61, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x53,
	0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x6b, 0x6d, 0x73,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a,
	0x10, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x1c, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x6b, 0x6d, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44,
	0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2e, 0x52, 0x61, 0x77, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x47, 0x54, 0x4c, 0x69, 0x53, 0x75, 0x6e, 0x6e, 0x79, 0x69, 0x2f, 0x63, 0x69,
	0x74, 0x61, 0x2d, 0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kms_proto_rawDescOnce sync.Once
	file_kms_proto_rawDescData = file_kms_proto_rawDesc
)

func file_kms_proto_rawDescGZIP() []byte {
	file_kms_proto_rawDescOnce.Do(func() {
		file_kms_proto_rawDescData = protoimpl.X.CompressGZIP(file_kms_proto_rawDescData)
	})
	return file_kms_proto_rawDescData
}

var file_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kms_proto_goTypes = []interface{}{
	(*GetCryptoInfoResponse)(nil),    // 0: kms.GetCryptoInfoResponse
	(*GenerateKeyPairRequest)(nil),   // 1: kms.GenerateKeyPairRequest
	(*GenerateKeyPairResponse)(nil),  // 2: kms.GenerateKeyPairResponse
	(*HashDataRequest)(nil),          // 3: kms.HashDataRequest
	(*VerifyDataHashRequest)(nil),    // 4: kms.VerifyDataHashRequest
	(*SignMessageRequest)(nil),       // 5: kms.SignMessageRequest
	(*SignMessageResponse)(nil),      // 6: kms.SignMessageResponse
	(*RecoverSignatureRequest)(nil),  // 7: kms.RecoverSignatureRequest
	(*RecoverSignatureResponse)(nil), // 8: kms.RecoverSignatureResponse
	(*proto.StatusCode)(nil),         // 9: common.StatusCode
	(*proto.Empty)(nil),              // 10: common.Empty
	(*types.RawTransactions)(nil),    // 11: blockchain.RawTransactions
	(*proto.HashResponse)(nil),       // 12: common.HashResponse
}
var file_kms_proto_depIdxs = []int32{
	9,  // 0: kms.GetCryptoInfoResponse.status:type_name -> common.StatusCode
	9,  // 1: kms.SignMessageResponse.status:type_name -> common.StatusCode
	9,  // 2: kms.RecoverSignatureResponse.status:type_name -> common.StatusCode
	10, // 3: kms.KmsService.GetCryptoInfo:input_type -> common.Empty
	1,  // 4: kms.KmsService.GenerateKeyPair:input_type -> kms.GenerateKeyPairRequest
	3,  // 5: kms.KmsService.HashData:input_type -> kms.HashDataRequest
	4,  // 6: kms.KmsService.VerifyDataHash:input_type -> kms.VerifyDataHashRequest
	5,  // 7: kms.KmsService.SignMessage:input_type -> kms.SignMessageRequest
	7,  // 8: kms.KmsService.RecoverSignature:input_type -> kms.RecoverSignatureRequest
	11, // 9: kms.KmsService.CheckTransactions:input_type -> blockchain.RawTransactions
	0,  // 10: kms.KmsService.GetCryptoInfo:output_type -> kms.GetCryptoInfoResponse
	2,  // 11: kms.KmsService.GenerateKeyPair:output_type -> kms.GenerateKeyPairResponse
	12, // 12: kms.KmsService.HashData:output_type -> common.HashResponse
	9,  // 13: kms.KmsService.VerifyDataHash:output_type -> common.StatusCode
	6,  // 14: kms.KmsService.SignMessage:output_type -> kms.SignMessageResponse
	8,  // 15: kms.KmsService.RecoverSignature:output_type -> kms.RecoverSignatureResponse
	9,  // 16: kms.KmsService.CheckTransactions:output_type -> common.StatusCode
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_kms_proto_init() }
func file_kms_proto_init() {
	if File_kms_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kms_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCryptoInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyPairRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKeyPairResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyDataHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverSignatureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kms_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecoverSignatureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kms_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kms_proto_goTypes,
		DependencyIndexes: file_kms_proto_depIdxs,
		MessageInfos:      file_kms_proto_msgTypes,
	}.Build()
	File_kms_proto = out.File
	file_kms_proto_rawDesc = nil
	file_kms_proto_goTypes = nil
	file_kms_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KmsServiceClient is the client API for KmsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KmsServiceClient interface {
	// Get crypto info
	GetCryptoInfo(ctx context.Context, in *proto.Empty, opts ...grpc.CallOption) (*GetCryptoInfoResponse, error)
	// Generate a KeyPair
	GenerateKeyPair(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error)
	// Hash data
	HashData(ctx context.Context, in *HashDataRequest, opts ...grpc.CallOption) (*proto.HashResponse, error)
	// Verify hash of data
	VerifyDataHash(ctx context.Context, in *VerifyDataHashRequest, opts ...grpc.CallOption) (*proto.StatusCode, error)
	// Sign a message
	SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error)
	// Recover signature
	RecoverSignature(ctx context.Context, in *RecoverSignatureRequest, opts ...grpc.CallOption) (*RecoverSignatureResponse, error)
	// check transactions
	CheckTransactions(ctx context.Context, in *types.RawTransactions, opts ...grpc.CallOption) (*proto.StatusCode, error)
}

type kmsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKmsServiceClient(cc grpc.ClientConnInterface) KmsServiceClient {
	return &kmsServiceClient{cc}
}

func (c *kmsServiceClient) GetCryptoInfo(ctx context.Context, in *proto.Empty, opts ...grpc.CallOption) (*GetCryptoInfoResponse, error) {
	out := new(GetCryptoInfoResponse)
	err := c.cc.Invoke(ctx, "/kms.KmsService/GetCryptoInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) GenerateKeyPair(ctx context.Context, in *GenerateKeyPairRequest, opts ...grpc.CallOption) (*GenerateKeyPairResponse, error) {
	out := new(GenerateKeyPairResponse)
	err := c.cc.Invoke(ctx, "/kms.KmsService/GenerateKeyPair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) HashData(ctx context.Context, in *HashDataRequest, opts ...grpc.CallOption) (*proto.HashResponse, error) {
	out := new(proto.HashResponse)
	err := c.cc.Invoke(ctx, "/kms.KmsService/HashData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) VerifyDataHash(ctx context.Context, in *VerifyDataHashRequest, opts ...grpc.CallOption) (*proto.StatusCode, error) {
	out := new(proto.StatusCode)
	err := c.cc.Invoke(ctx, "/kms.KmsService/VerifyDataHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) SignMessage(ctx context.Context, in *SignMessageRequest, opts ...grpc.CallOption) (*SignMessageResponse, error) {
	out := new(SignMessageResponse)
	err := c.cc.Invoke(ctx, "/kms.KmsService/SignMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) RecoverSignature(ctx context.Context, in *RecoverSignatureRequest, opts ...grpc.CallOption) (*RecoverSignatureResponse, error) {
	out := new(RecoverSignatureResponse)
	err := c.cc.Invoke(ctx, "/kms.KmsService/RecoverSignature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kmsServiceClient) CheckTransactions(ctx context.Context, in *types.RawTransactions, opts ...grpc.CallOption) (*proto.StatusCode, error) {
	out := new(proto.StatusCode)
	err := c.cc.Invoke(ctx, "/kms.KmsService/CheckTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KmsServiceServer is the server API for KmsService service.
type KmsServiceServer interface {
	// Get crypto info
	GetCryptoInfo(context.Context, *proto.Empty) (*GetCryptoInfoResponse, error)
	// Generate a KeyPair
	GenerateKeyPair(context.Context, *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error)
	// Hash data
	HashData(context.Context, *HashDataRequest) (*proto.HashResponse, error)
	// Verify hash of data
	VerifyDataHash(context.Context, *VerifyDataHashRequest) (*proto.StatusCode, error)
	// Sign a message
	SignMessage(context.Context, *SignMessageRequest) (*SignMessageResponse, error)
	// Recover signature
	RecoverSignature(context.Context, *RecoverSignatureRequest) (*RecoverSignatureResponse, error)
	// check transactions
	CheckTransactions(context.Context, *types.RawTransactions) (*proto.StatusCode, error)
}

// UnimplementedKmsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKmsServiceServer struct {
}

func (*UnimplementedKmsServiceServer) GetCryptoInfo(context.Context, *proto.Empty) (*GetCryptoInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCryptoInfo not implemented")
}
func (*UnimplementedKmsServiceServer) GenerateKeyPair(context.Context, *GenerateKeyPairRequest) (*GenerateKeyPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKeyPair not implemented")
}
func (*UnimplementedKmsServiceServer) HashData(context.Context, *HashDataRequest) (*proto.HashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HashData not implemented")
}
func (*UnimplementedKmsServiceServer) VerifyDataHash(context.Context, *VerifyDataHashRequest) (*proto.StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyDataHash not implemented")
}
func (*UnimplementedKmsServiceServer) SignMessage(context.Context, *SignMessageRequest) (*SignMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (*UnimplementedKmsServiceServer) RecoverSignature(context.Context, *RecoverSignatureRequest) (*RecoverSignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverSignature not implemented")
}
func (*UnimplementedKmsServiceServer) CheckTransactions(context.Context, *types.RawTransactions) (*proto.StatusCode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTransactions not implemented")
}

func RegisterKmsServiceServer(s *grpc.Server, srv KmsServiceServer) {
	s.RegisterService(&_KmsService_serviceDesc, srv)
}

func _KmsService_GetCryptoInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).GetCryptoInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/GetCryptoInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).GetCryptoInfo(ctx, req.(*proto.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_GenerateKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).GenerateKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/GenerateKeyPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).GenerateKeyPair(ctx, req.(*GenerateKeyPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_HashData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).HashData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/HashData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).HashData(ctx, req.(*HashDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_VerifyDataHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDataHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).VerifyDataHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/VerifyDataHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).VerifyDataHash(ctx, req.(*VerifyDataHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_SignMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).SignMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/SignMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).SignMessage(ctx, req.(*SignMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_RecoverSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).RecoverSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/RecoverSignature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).RecoverSignature(ctx, req.(*RecoverSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KmsService_CheckTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.RawTransactions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KmsServiceServer).CheckTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kms.KmsService/CheckTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KmsServiceServer).CheckTransactions(ctx, req.(*types.RawTransactions))
	}
	return interceptor(ctx, in, info, handler)
}

var _KmsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kms.KmsService",
	HandlerType: (*KmsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCryptoInfo",
			Handler:    _KmsService_GetCryptoInfo_Handler,
		},
		{
			MethodName: "GenerateKeyPair",
			Handler:    _KmsService_GenerateKeyPair_Handler,
		},
		{
			MethodName: "HashData",
			Handler:    _KmsService_HashData_Handler,
		},
		{
			MethodName: "VerifyDataHash",
			Handler:    _KmsService_VerifyDataHash_Handler,
		},
		{
			MethodName: "SignMessage",
			Handler:    _KmsService_SignMessage_Handler,
		},
		{
			MethodName: "RecoverSignature",
			Handler:    _KmsService_RecoverSignature_Handler,
		},
		{
			MethodName: "CheckTransactions",
			Handler:    _KmsService_CheckTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms.proto",
}
